### ISSUE TITLE
Homepage should be redirected programmatically to GW Tech Radar

### ISSUE THREAD

**Issue by chrisdiao** [k8-proxy/p-k8-tech-radar#13]
User will no longer provide the google sheet link information in the home page, instead the app will process programmatically and have the user redirected to the GW tech radar, same as the image below 

![image.png](https://images.zenhubusercontent.com/5f43cee726e80382e54a0b0f/d03aa215-d31d-4bfc-bed1-ac273a8e201f)

**Comment by hunnain** [comment]
Task Completed

**Comment by chrisdiao** [comment]
@hunnain , this has been verified and confirmed that this already working as expected.
